sudo: required

language: bash

install:
    # Dependencies
    - sudo apt-get -qq update
    - sudo pip install --upgrade -qq pip
    - sudo apt-get -qq install cdparanoia cdrdao flac libcdio-dev libiso9660-dev libsndfile1-dev python-cddb python-gst0.10 python-gobject python-musicbrainzngs python-mutagen python-setuptools sox swig
    - sudo pip install pycdio

    # Testing dependencies
    - sudo apt-get -qq install python-twisted-core

    # Build bundled C utils
    - cd src
    - sudo make install
    - cd ..

    # Installing
    - sudo python setup.py install

script:
    - python -m unittest discover
